# Generated by Django 3.2.9 on 2021-11-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0004_hiretuber_tb_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiretuber',
            old_name='tb_city',
            new_name='tb_place',
        ),
    ]
