# Generated by Django 3.2.9 on 2021-11-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0005_rename_tb_city_hiretuber_tb_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiretuber',
            name='tb_place',
        ),
    ]
