# Generated by Django 3.2.9 on 2021-11-23 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0006_remove_hiretuber_tb_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiretuber',
            name='tuber_city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
