# Generated by Django 3.2.9 on 2021-11-18 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/team/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
