# Generated by Django 3.2.9 on 2021-11-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacttubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.TextField(),
        ),
    ]
