# Generated by Django 3.2.9 on 2021-11-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socallinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_link', models.CharField(max_length=255)),
                ('insta_link', models.CharField(max_length=255)),
                ('twitter_link', models.CharField(max_length=255)),
                ('yt_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='fb_link',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='insta_link',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='yt_link',
        ),
    ]
