# Generated by Django 3.2.9 on 2021-11-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0002_hiretuber_tuber_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiretuber',
            name='tuber_city',
        ),
    ]
