# Generated by Django 3.2.9 on 2021-11-23 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0003_remove_hiretuber_tuber_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiretuber',
            name='tb_city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
