# Generated by Django 3.2.9 on 2021-11-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacttubers', '0002_auto_20211114_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
